### PR TITLE
Update to the latest pulumi{,-terraform-bridge}.

### PR DESCRIPTION
**Pull request by pgavlin**
These updates bring in schema-based NodeJS codegen. A few tweaks to
resources.go were necessary to ensure that all tokens used by this
package are in a consistent format, i.e. `aws:module/member:member`.

### CODE REVIEW

**Comment by pgavlin** [comment]
> Do we really want to depend pulumi/pulumi@master?

In this case, yes: the latest stable release doesn't have the changes we need.

**Comment by pgavlin** [comment]
Not sure what's causing the Python diffs. I'll investigate this afternoon.

**Comment by stack72** [comment]
@pgavlin I think we can close this out as @mikhailshilkov already upgraded this provider to the new generator

**Comment by lukehoban** [comment]
Closing out.  https://github.com/pulumi/pulumi-aws/pull/921 is a newer PR that updates these deps.

**Pull request closed without merging**
