### PR TITLE
Remove QuickSight hack in favor of bridge change

### PR DESCRIPTION
**Pull request by iwahbe**
Taking advantage of pulumi/pulumi-terraform-bridge#1548, this PR removes the quicksight schema customizations since `Omit` now does the right thing on its own.

This has the advantage of removing these unusable mappings from `bridge-metadata.json`.

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Does the lack of changes in the sdk mean that the change does exactly the same as manually omitting the types?

**Comment by iwahbe** [comment]
> Does the lack of changes in the sdk mean that the change does exactly the same as manually omitting the types?

Yes.

**Comment by t0yv0** [comment]
This needs `go mod tidy`. LGTM if tests pass.

**Review by t0yv0 — APPROVED** [review]

**Pull request merged**
