### PR TITLE
Upgrade terraform provider aws to v5.32.0

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes https://github.com/pulumi/pulumi-aws/issues/3253

This PR upgrades the provider to match upstream provider version v5.32.0.

List of unusual things that defeated upgrade-provider and required manual intervention:

- The patch for elbv2 target workaround in #2517 does not apply cleanly to new upstream, had to be redone; I've tested manually that 2517 does not reproduce on top of the new provider, but need to backlog adding a test for it; the relevant ticket is in https://github.com/pulumi/pulumi-aws/issues/2749

- Upstream is gradually removing AWS Go SDK v1. This affected legacy bucket resource that Pulumi retains in spite of upstream having it removed. This is now working again but required another invasive patch to undo upstream changes.

- New "verified permissions" module needed to be registered in resources.go to support automatic module inference.

- Several new Plugin Framework based resources required patching to support tags; this is slowing us down until we can implement https://github.com/pulumi/pulumi-aws/issues/2962 

- Run test of provider shim was breaking as it didn't get all the dependencies, now fixed

- Patch from https://github.com/pulumi/pulumi-aws/pull/3290 wouldn't apply because of wrong format (`make upstream.rebase` broken) - had to reformat it

### CODE REVIEW

**Comment by t0yv0** [comment]
OK looks like there's a build bug lurking somewhere, running `make build_python locally keeps adding things to replacements.json that are already present there.

```
t0yv0@Antons-MacBook-Pro> grep redrive_allow provider/replacements.json                                                                                                                                                                  ~/code/pulumi-aws-3
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
      "old": "resource \"aws_sqs_queue_redrive_allow_policy\" \"terraform_queue_redrive_allow_policy\" {\n",
      "new": "resource \"aws_sqs_queue_redrive_allow_policy\" \"TODO_queue_redrive_allow_policy\" {\n"
```

**Comment by iwahbe** [comment]
> OK looks like there's a build bug lurking somewhere, running `make build_python locally keeps adding things to replacements.json that are already present there.
> 

Fixing the TODOs should work around the build bug. Interestingly, the build bug actually forces us to address the TODOs, which is helpful.

**Comment by t0yv0** [comment]
> Interestingly, the build bug actually forces us to address the TODOs, which is helpful.

🤦‍♂️  That is not the approach to error messages I was hoping to see.

**Comment by iwahbe** [comment]
> > Interestingly, the build bug actually forces us to address the TODOs, which is helpful.
> 
> 🤦‍♂️ That is not the approach to error messages I was hoping to see.

It's a bug. We should fix the bug. 😃 I'm just calling out that the broken behavior has benefits, and we should consider if it's worth trying to keep the benefits when we fix the bug.

**Review by iwahbe — APPROVED** [review]
LGTM

**Pull request merged**
