### PR TITLE
Expand upgrade tests

### PR DESCRIPTION
**Pull request by VenelinMartinov**
This adds upgrade tests for 22 more of our top 50 resources, bringing the number to 46/50.

The last two resources are BucketPolicy and AccessKey - I've removed these two from the tests since they cause issues:
 - BucketPolicy is yielding 403 - seems like it needs some special permissions on the key and that needs some additional setup for CI.
 - AccessKey is sensitive so I've opted for keeping it out of the tests. Having it in an upgrade tests causes the GRPC to get logged, which contain the plaintext values of the access key.
 - ACM tests are blocked by https://github.com/pulumi/pulumi-aws/issues/3617

fixes https://github.com/pulumi/pulumi-aws/issues/3470

- [X] aws:iam:role
- [X] aws:ec2:securitygroup
- [X] aws:iam:rolepolicyattachment
- [X] aws:s3:bucket
- [X] aws:ec2:vpc
- [X] aws:ec2:subnet
- [x] aws:ec2:internetgateway
- [x] aws:iam:policy
- [x] aws:ec2:routetable
- [x] aws:ec2:routetableassociation
- [X] aws:ecr:repository
- [x] aws:ec2:eip
- [X] aws:route53:record
- [X] aws:cloudwatch:loggroup
- [x] aws:ec2:natgateway
- [X] aws:lambda:function
- [x] aws:ec2:route
- [x] aws:ec2:securitygrouprule
- [x] aws:ecs:cluster
- [x] aws:lb:targetgroup
- [x] aws:lb:loadbalancer
- [x] aws:lb:listener
- [ ] aws:acm:certificate
- [x] aws:ecs:taskdefinition
- [ ] aws:s3:bucketpolicy
- [X] aws:lambda:permission
- [x] aws:ecs:service
- [x] aws:rds:subnetgroup
- [X] aws:iam:instanceprofile
- [x] aws:iam:rolepolicy
- [X] aws:ecr:lifecyclepolicy
- [x] aws:iam:user
- [x] aws:ec2:instance
- [x] aws:cloudfront:distribution
- [x] aws:s3:bucketpublicaccessblock
- [X] aws:rds:instance
- [X] aws:route53:zone
- [ ] aws:acm:certificatevalidation
- [X] aws:eks:cluster
- [X] aws:kms:key
- [x] aws:s3:bucketobject
- [X] aws:secretsmanager:secret
- [X] aws:sqs:queue
- [ ] aws:iam:accesskey
- [X] aws:cloudwatch:eventrule
- [X] aws:cloudwatch:eventtarget
- [X] aws:sns:topic
- [X] aws:iam:openidconnectprovider
- [x] aws:secretsmanager:secretversion
- [X] aws:dynamodb:table

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
BucketPolicy is yielding 403 - seems like it needs some special permissions.

AccessKey is sensitive so I've opted for keeping it out of the tests.

**Comment by VenelinMartinov** [comment]
Looks like the ACM resource custom timeout on Create is not honoured in the baseline version 5.42.

**Review by iwahbe — APPROVED** [review]
Looks like something is wrong with the ACM test, but otherwise LGTM.

**Comment by t0yv0** [comment]
Very nice! Almost there.

**Pull request merged**
