### PR TITLE
Enable SourceLink with embedded PDB

### LINKED ISSUE #1036: Enable SourceLink and embed PDB symbols
[SourceLink](https://github.com/dotnet/sourcelink) is essential and would make it easy to step _into_ Pulumi C# source supplied as NuGet packages.

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #1036. Similar to https://github.com/pulumi/pulumi/pull/4967.

### CODE REVIEW

**Comment by gitfool** [comment]
Unrelated build failure:
```
error: working tree is not clean, aborting!
```

**Comment by gitfool** [comment]
@mikhailshilkov PTAL

**Comment by mikhailshilkov** [comment]
@gitfool The build failure is related: you can't change the `csproj` file manually because it's auto-generated. The provider needs to update to the latest `pulumi/pulumi` (in Go) to start generating your changes. The only other work needed is to bump the `dotnet` versions.

**Comment by gitfool** [comment]
@mikhailshilkov okay, so I should revert the change to [sdk/dotnet/Pulumi.Aws.csproj](https://github.com/pulumi/pulumi-aws/pull/1037/files#diff-4cff54c81c28caa95a32a4a852725c49).

I'm not sure exactly where to "update to the latest `pulumi/pulumi`". If you could give more detailed info, I'll get this over the line.

**Comment by mikhailshilkov** [comment]
My plan is to go through a normal release cycle here:

- Release a new version of `pulumi/pulumi` (2.7, I think it's planned for later today)
- During the next update of the AWS provider, @stack72 would bump `pulumi/pulumi` to 2.7
- The same will eventually happen for all providers

**Comment by gitfool** [comment]
@stack72 gentle prod... please update Pulumi for the next release so we can get NuGet symbols for dotnet. 😉

**Comment by stack72** [comment]
Closing this out as it's been taken care of in master and as part of the release process that has just started

**Comment by gitfool** [comment]
@stack72 the symbols are not in the `Pulumi.Aws` NuGet [package](https://www.nuget.org/packages/Pulumi.Aws/3.0.0).

It looks like this is because the [Pulumi.Aws.csproj](https://github.com/pulumi/pulumi-aws/pull/1037/commits/dad5566d92a40299aa1ca52a6b5a761a346bbf08) file was not updated / regenerated with the required properties. Maybe I misunderstood but I thought this would be done by the upgrade to the latest Pulumi. 😕

**Comment by stack72** [comment]
ok, so then I didn't realise that work needs to happen in the codegen in pulumi/pulumi to make this happen - I will reopen this now so I will add the related changes upstream

**Comment by stack72** [comment]
@gitfool I have no forgotten you here! I am looking to get this rolled out this week

**Comment by stack72** [comment]
Closed via #1082

**Pull request closed without merging**
