### PR TITLE
Upgrade to v5.1.0

### LINKED ISSUE #2535: Upgrade terraform-provider-aws to v5.0.0
Release details: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

### LINKED ISSUE #2536: Upgrade terraform-provider-aws to v5.0.1
Release details: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.1

### LINKED ISSUE #2540: Upgrade terraform-provider-aws to v5.1.0
Release details: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.1.0

### PR DESCRIPTION
**Pull request by rquitales**
Upgrade our patched upstream fork to target the next major release, v5.1.0.

- Removed the quicksight dashboard and analytics definition property for now which makes the resource unuable, but allows us to release until Ensure shorter tokens for object types  pulumi-terraform-bridge#1118 is resolved
- Uses PlanState for diffing strategy fix diffing error with missing attributes
- Update tests to not use deprecated and removed fields

Fixes #2535 
Fixes #2536 
Fixes #2540

### CODE REVIEW

**Review by kpitzen — APPROVED** [review]
Each step here looks reasonable to me - it's hard to review the actual diffs post-generation, but from what I can tell, this appears to do what we expect.

Do we know how many of the breaking changes in the schema-tools comment line up with the announcement from the upstream 5.0.0 release notes?

**Review by thomas11 — CHANGES_REQUESTED** [review]
All the Go examples in schema.json import `github.com/pulumi/pulumi-aws/sdk/v5` - that should be v6, right?

**Comment by rquitales** [comment]
Most of the changes line up with the breaking changes announcement in v5. The following did not:

- Resource "aws:lightsail/instance:Instance" missing output "ipv6Address"
- Resource "aws:autoscaling/group:Group" missing input "tagsCollection"
- Resource "aws:autoscaling/group:Group" missing output "tagsCollection"
- Type "aws:msk/ClusterBrokerNodeGroupInfo:ClusterBrokerNodeGroupInfo" missing property "ebsVolumeSize"
- Type "aws:wafv2/WebAclRuleStatementManagedRuleGroupStatement:WebAclRuleStatementManagedRuleGroupStatement" missing property "excludedRules"
- Type "aws:wafv2/WebAclRuleStatementRuleGroupReferenceStatement:WebAclRuleStatementRuleGroupReferenceStatement" missing property "excludedRules"
- Type "aws:wafv2/WebAclLoggingConfigurationRedactedFieldSingleQueryArgument:WebAclLoggingConfigurationRedactedFieldSingleQueryArgument" missing
- Type "aws:wafv2/WebAclLoggingConfigurationRedactedFieldAllQueryArguments:WebAclLoggingConfigurationRedactedFieldAllQueryArguments" missing
- Type "aws:ec2/RouteTableRoute:RouteTableRoute" missing property "instanceId"
- Resource "aws:ec2/route:Route" missing input "instanceId"

**Comment by thomas11** [comment]
> > All the Go examples in schema.json import `github.com/pulumi/pulumi-aws/sdk/v5` - that should be v6, right?
> 
> Good catch. Fixed!

Thanks! The `VERSION_PREFIX` you specified on the command line should be the new default in this branch, though, so we don't need to remember it.

**Comment by rquitales** [comment]
> > > All the Go examples in schema.json import `github.com/pulumi/pulumi-aws/sdk/v5` - that should be v6, right?
> > 
> > 
> > Good catch. Fixed!
> 
> Thanks! The `VERSION_PREFIX` you specified on the command line should be the new default in this branch, though, so we don't need to remember it.

I'll make the necessary changes in a follow-up PR to not restart CI for this.

**Review by thomas11 — APPROVED** [review]

**Pull request merged**
