### PR TITLE
AWS m6a instances support #1791

### PR DESCRIPTION
**Pull request by clamo**
This PR is regarding issue #1791 - AWS m6a instances not supported

### CODE REVIEW

**Review by jkodroff — APPROVED** [review]
Thanks so much for the contribution!

**Comment by stack72** [comment]
@jkodroff we need to build the schema to pick up these changes or we will have a failed build in main line

**Review by jkodroff — CHANGES_REQUESTED** [review]
@clamo Per Paul's comment above, I need to change my review to request changes. Could you run the following commands and resubmit your PR?

* `make tfgen`
* `make build_sdks`

This will allow the build to pass. Note that these commands may take a while to run - on the order of 10 minutes.

**Review by jkodroff — APPROVED** [review]

**Pull request merged**
