### PR TITLE
Upgrade terraform provider aws to v5.25.0

### LINKED ISSUE #2983: Upgrade terraform-provider-aws to v5.25.0
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### PR DESCRIPTION
**Pull request by t0yv0**
[Upstream v5.25.0 release notes](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.25.0)

Fixes #2983, #2904, #2971, #2900

- [x] Rebuild eks.Cluster patches; upstream moved to AWS SDK v2 for Go, patches needed updates as well
- [x] Fix https://github.com/pulumi/pulumi-terraform-bridge/issues/1523 in the bridge
- [x] Update bridge to include https://github.com/pulumi/pulumi-terraform-bridge/pull/1521 and https://github.com/pulumi/pulumi-terraform-bridge/pull/1520 fixes affecting P1s in pulumi-aws
- [x] Build a Pulumi test for EKS Cluster add-on removal -> turns out the property is a no-op, not needed

### CODE REVIEW

**Comment by t0yv0** [comment]
Actually the addon-related property seems to be a no-op. https://github.com/pulumi/pulumi-aws/issues/3009 <- will follow up later on with deprecating it.

**Review by iwahbe — APPROVED** [review]
LGTM

**Comment by t0yv0** [comment]
finite incantatem

**Pull request merged**
