### PR TITLE
Ensure autonamed FIFO Queue has ".fifo" suffix

### LINKED ISSUE #967: Support autonaming of SQS fifo queues
SQS FIFO queue names must have a ".fifo" suffix. This does not play well will auto-naming because the random hex will be tacked on at the end yielding an invalid name. I suggest that the ".fifo" suffix should be added by pulumi when autonaming a fifo queue.

Here is some example C# code:

```csharp

    // fails on AWS because name must end with .fifo
    var q1 = new Queue("myqueue", new QueueArgs {
        FifoQueue = true
    });

    //fails in pulumi with the message:
    //only alphanumeric characters and hyphens allowed in "name"
    var q2 = new Queue("myqueue.fifo", new QueueArgs {
        FifoQueue = true
   });

   //explicitly assigning a name works but does not use autonaming 
   var q3 = new Queue("myqueue" new QueueArgs {
        FifoQueue = true,
        Name = "myqueue.fifo"
    });
```

### PR DESCRIPTION
**Pull request by lukehoban**
Fixes #967.

### CODE REVIEW

**Review by stack72 — APPROVED** [review]
This is going to roll out the import docs for AWS which I was going to start on Monday as long as you are on with that, then I am too

**Comment by lukehoban** [comment]
> This is going to roll out the import docs for AWS which I was going to start on Monday as long as you are on with that, then I am too

Do need to wait to merge https://github.com/pulumi/pulumi-terraform-bridge/pull/297 first, so that we can update this PR to a `master` commit of the bridge dependency.  Also not sure if you are okay with picking up a new bridge in the middle of the import docs work.  Happy for this to wait a couple days.

**Comment by stack72** [comment]
So the import docs work is at a point now we can ship it and iterate it as we see fit

Ideally we'd merge the bridge work and then cut a tag but for the purposes of this fix, we can do it this way and I will update all repos to the new tag at the start of the week - this just gets a fix over the line at the same time :)

**Comment by stack72** [comment]
Superceded by #1257

**Pull request closed without merging**
