### PR TITLE
fix: invocation of getEngineVersion returns an error

### LINKED ISSUE #4043: As of 6.37.0 `invocation of aws:rds/getEngineVersion:getEngineVersion returned an error`.
### Describe what happened

As of 6.37.0 the code below in the sample program returns the following error: 
```
an unhandled error occurred: program failed:
    waiting for RPCs: rpc error: code = Unknown desc = invocation of aws:rds/getEngineVersion:getEngineVersion returned an error: invoking aws:rds/getEngineVersion:getEngineVersion: 1 error occurred:
        * reading RDS engine versions: InvalidParameterCombination: RDS can't find a default engine version.
        status code: 400, request id: c5c4bfc9-2718-4046-aaac-ee27a76db0f9
```

### Sample program

```golang
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/rds"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		engineParams := rds.GetEngineVersionOutput(ctx, rds.GetEngineVersionOutputArgs{
			Engine:  pulumi.String("aurora-postgresql"),
			Version: pulumi.String("15.2"),
			Filters: rds.GetEngineVersionFilterArray{
				rds.GetEngineVersionFilterArgs{
					Name: pulumi.String("engine-mode"),
					Values: pulumi.ToStringArray([]string{
						"provisioned",
					}),
				},
			},
		})

		ctx.Export("rdsVersion", engineParams.Version())

		return nil
	})
}
```

### Log output

    error: an unhandled error occurred: program failed:
    waiting for RPCs: rpc error: code = Unknown desc = invocation of aws:rds/getEngineVersion:getEngineVersion returned an error: invoking aws:rds/getEngineVersion:getEngineVersion: 1 error occurred:
        * reading RDS engine versions: InvalidParameterCombination: RDS can't find a default engine version.
        status code: 400, request id: c5c4bfc9-2718-4046-aaac-ee27a76db0f9

### Affected Resource(s)

_No response_

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.119.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   6.37.0
language  go    unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
A patch was introduced via #3757 due to [a bug in
pulumi-terraform-bridge](https://github.com/pulumi/pulumi-terraform-bridge/issues/1809).

The underlying bridge issue has now been fixed so I am removing the patch and restoring the original terraform behavior.

fixes #4043

### CODE REVIEW

**Review by mjeffryes — APPROVED** [review]
I'm a little unclear on the context here: 

We introduced a patch to fix a panic; did that patch always produce this error? or did it start producing the error after we picked up the tfbridge change that fixed the underlying cause for the panic?

**Review by flostadler — APPROVED** [review]
The change lgtm.
I think for the future we need to be more careful with adding more tests for patches and following up with removing them when the underlying issue is fixed.

In this case the bridge fix was released 3 weeks ago, but we're missing some sort of automation to make us aware of this

**Comment by corymhall** [comment]
> We introduced a patch to fix a panic; did that patch always produce this error? or did it start producing the error after we picked up the tfbridge change that fixed the underlying cause for the panic?

I am not 100% sure. There were a couple of bug fixes in upstream that we had to revert/incorporate into our revert/patch. We had a test for the panic that was still passing, but it wasn't testing this specific use case with other properties provided. Since the linked issue says since `6.37.0` and our patch was introduced in `6.28.2` my hunch would be that the bug was introduced attempting to rebase upstream changes into our patch during an upgrade. 

> In this case the bridge fix was released 3 weeks ago, but we're missing some sort of automation to make us aware of this

Yeah it would be nice to have automation to gather linked issues and label them with `fixed-upstream` or something.

**Pull request merged**
