### PR TITLE
Add support for T3a instance types

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #698

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
LGTM.

**Comment by lukehoban** [comment]
I assume there are lots of other instances missing?  Should we do a more complete pass to bring this up to date?

In general - given that missing values in these enums  make it *seem* like the missing options are unsupported - seems like we need to put some system or process in place to keep them up to date on at least a ~monthly basis. Same applies to all other enums.

**Comment by stack72** [comment]
@lukehoban yes, I will be doing this as soon as I have fixed up some of the things for 0.26

We need to investigate a better way of managing this

**Comment by lukehoban** [comment]
I continue to believe we should automate or semi-automate generation of these enums from primary sources.  

For examples - instances are available here: https://github.com/aws/aws-sdk-go/blob/master/models/apis/ec2/2016-11-15/api-2.json#L15131

**Comment by stack72** [comment]
@lukehoban I 100% agree with you!

**Pull request merged**
