### PR TITLE
Upstream v5.48.0

### PR DESCRIPTION
**Pull request by t0yv0**
Upgrades upstream to v5.48.0

Fixes https://github.com/pulumi/pulumi-aws/issues/3890

### CODE REVIEW

**Comment by t0yv0** [comment]
Looks like the regression test is catching an actual problem. We introduced custom retry for KMS condition on lambda invocation and it has regressed because upstream is moving from Go SDK v1 to Go SDK V2:

https://github.com/pulumi/pulumi-aws/pull/3234

**Comment by t0yv0** [comment]
Fixed the patch to use AWS SDKv2 and trying this again.

**Comment by t0yv0** [comment]
aws_bedrockagent_agent_knowledge_base_association mapping to bedrock/agentAgentKnowledgeBaseAssociation.AgentAgentKnowledgeBaseAssociation is unfortunate, perhaps can do better here.

**Comment by t0yv0** [comment]
TestAccWebserverComp flake.

**Review by corymhall — APPROVED** [review]

**Comment by t0yv0** [comment]
I'm running into some difficulties with moving bedrockanalysis resources namely https://github.com/pulumi/pulumi-terraform-bridge/issues/1937

Going to backlog this and take the change later.

**Pull request merged**
