### PR TITLE
Upgrade pulumi terraform bridge to v3.62.0

### PR DESCRIPTION
**Pull request by mjeffryes**
generated with 
`upgrade-provider pulumi/pulumi-aws --target-bridge-version v3.62.0 --kind bridge`

### CODE REVIEW

**Comment by mjeffryes** [comment]
Hmm...there seems to be some regression in docs with this change.

**Comment by t0yv0** [comment]
TypeError: _configure() missing 1 required positional argument: 'compute_type' ? 

One second, I think this is something we blocked the 3.62.0 https://github.com/pulumi/pulumi-terraform-bridge/issues/1439 release on

**Comment by t0yv0** [comment]
Let's investigate tomorrow. This could be another issue in p/p but would be good to eliminate the possibility that the test/example was somehow quietly incorrect until now.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi/issues/14274 this is a platform bug.

**Comment by iwahbe** [comment]
Closing in favor of https://github.com/pulumi/pulumi-aws/pull/2918.

**Pull request closed without merging**
