### PR TITLE
Use Go 1.20.x

### PR DESCRIPTION
**Pull request by t0yv0**
Upgrade CI to build and test on Go 1.20.x from Go 1.19.x.

### CODE REVIEW

**Review by rquitales — APPROVED** [review]

**Review by rquitales — CHANGES_REQUESTED** [review]
Just realised, can you also update the Golang version in `provider/go.mod` to point to Go v1.20 as well? Since we'll need it for upstream dependencies that use newer Go v1.20 features.

**Comment by t0yv0** [comment]
Sure added.

**Review by rquitales — APPROVED** [review]

**Comment by t0yv0** [comment]
```
    aws:ec2:InternetGateway (test):
      error: 1 error occurred:
      	* updating urn:pulumi:p-it-fv-az471-9-alb-new-py-60454d0b::alb-legacy-py::aws:ec2/internetGateway:InternetGateway::test: 1 error occurred:
      	* updating EC2 Internet Gateway (igw-086504add14ec4a3b): error attaching EC2 Internet Gateway (igw-086504add14ec4a3b) to VPC (vpc-0ab2dcaa778377b4b): Resource.AlreadyAssociated: resource igw-086504add14ec4a3b is already attached to network vpc-0ab2dcaa778377b4b
      	* ```

Some issues with account cleanup?

**Comment by rquitales** [comment]
CI test appears to have failed due to improper cleanup from the last run. Manually deleted the resources in AWS and rerunning tests now.

**Pull request merged**
