### PR TITLE
Add missing InstanceTypes

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Resolves https://github.com/pulumi/pulumi-aws/issues/3800

Done with 

```
aws ec2 describe-instance-types | jq  ".InstanceTypes[]" | jq -c -r '"{Name: \"" + (.InstanceType | gsub("\\.";"_") | ./"" | first |= ascii_upcase | add) + "\", Value: \"" + .InstanceType + "\"},"' | sort
```

and then cleaning it up manually with replaces and reordering to minimize the difference.

### CODE REVIEW

**Comment by t0yv0** [comment]
Can you add a test that runs this

```
aws ec2 describe-instance-types | jq  ".InstanceTypes[]" | jq -c -r '"{Name: \"" + (.InstanceType | gsub("\\.";"_") | ./"" | first |= ascii_upcase | add) + "\", Value: \"" + .InstanceType + "\"},"' | sort
```

Or equivalent and fails when it's out of sync? Would be awesome. Then we'll auto maintain this in-sync.

**Comment by mikhailshilkov** [comment]
> Then we'll auto maintain this in-sync.

This is one step extra... We'd need a few targeted replacements to satisfy all the convensions. Probably a Go function on top of `jq`.

**Comment by t0yv0** [comment]
Right on! Perhaps copilot can help write something in pure go too to avoid the JQ bit. Just a thought. I wouldn't block to merge this can backlog but would be nice.

**Comment by mikhailshilkov** [comment]
Closing in favor of https://github.com/pulumi/pulumi-aws/pull/3823

**Pull request closed without merging**
