### PR TITLE
Patch upstream doc to be an H3 and display as part of the Example Usage section

### PR DESCRIPTION
**Pull request by guineveresaenger**
Partial and temporary hack for https://github.com/pulumi/pulumi-aws/issues/2624.
Adds a patch that rewrites the "CloudWatch Logging and Permission" section as a nested H3 example, which gets rid of the inline code display at the top of out [Lambda Function landing page](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/). 

Note:
Elides display the incorrect "Lambda retries" section. A full fix for #2624 will address this and bring it back as the [description-only section that it is](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#lambda-retries).
This is a temporary hack and should be fully addressed via #2624, after which this patch should be removed.

The unrelated patch churn seems legitimate:
 - the deleted patch was included in an earlier patch 0036
 - the changed function title in 0022 is the patch anchor and does not affect our patch content.
---

Here's a screenshot of what the page should look like in the registry (please excuse the tiny image, but you can see the improvement)
Screenshot 2024-02-09 at 11 14 59 AM

### CODE REVIEW

**Comment by sean1588** [comment]
@guineveresaenger  thanks this looks great! 🎉  I am not too familiar with the code and how stuff works in this repo, so I'll leave that for others to approve, but I fully support doing this patch as a quick fix.

**Comment by t0yv0** [comment]
Could we avoid using a patch here?

**Comment by t0yv0** [comment]
Also, terribly sorry for the nasty merge but could we land https://github.com/pulumi/pulumi-aws/pull/3411 first 🙏

**Comment by t0yv0** [comment]
You could move the markdown code from upstream into the repo proper, then you could link it to the resource via .Docs:

```
		pi := tfbridge.ProviderInfo{
			P:       shimv2.NewProvider(p),
			Name:    "azurerm",
			Version: "0.0.1",
			Resources: map[string]*tfbridge.ResourceInfo{
				"azurerm_web_pubsub_custom_certificate": {
					Tok:  "azure:webpubsub/customCertificate:CustomCertificate",
					Docs: &tfbridge.DocInfo{Markdown: md},
				},
			},
		}
```

To be fair, the patch has the advantage that if upstream keeps changing this doc keeps changing also. But perhaps this doc is so important we'd rather maintain in-repo?

I can approve the patch just offering for your alternative consideration. I'm not having a good time maintaining these patches, and was thinking we need to improve this workflow anyway to make it easier.

**Review by t0yv0 — APPROVED** [review]

**Comment by guineveresaenger** [comment]
I prefer a patch here precisely so the doc doesn't get stale. 

Let's cut the release first and I'll rework this. Have a fantastic weekend @t0yv0 !

**Pull request merged**
