### PR TITLE
Add enum values in `aws.iam.ManagedPolicy`

### PR DESCRIPTION
**Pull request by tenwit**
Added `AmazonSSMAutomationApproverAccess`, `AmazonSSMDirectoryServiceAccess`,
and `AmazonSSMPatchAssociation`.

Did not add `AmazonSSMServiceRolePolicy` because it is not for general
use. AWS states "You cannot attach, detach, modify, or delete this
policy."

### CODE REVIEW

**Comment by tenwit** [comment]
Resolves issue #1195

**Comment by tenwit** [comment]
Looks like the build failure is caused by formatting changes. I committed changes made automatically by the toolchain on my machine (WSL2), and the same changes made by the CI toolchain is producing slightly different results.
I'll pull the correctly-formatted code from before the commit, and merge it manually.

**Comment by tenwit** [comment]
Ok I've got past the bad formatting. I'm guessing the remaining test failures are due to not have some credentials set up somewhere, but I haven't seen any docs on what values need to be set, or where. Looking for guidance from a Pulumi contributor...

**Comment by stack72** [comment]
Hi @tenwit 

I will pull this into my master branch and run the tests from there :) Thank you so much for this!

Paul

**Pull request merged**
