### PR TITLE
Add functionality to expose EKS KubeConfig on the Cluster resource

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #478

### CODE REVIEW

**Comment by lukehoban** [comment]
I’m not sure we want to add one-off helpers like this in this library. We already have an EKS package with helpers for EKS. If we think this is valuable - I’d suggest we add it there. Or alternatively, contribute it to as a data source in the upstream provider to that it is available for all Pulumi languages. 

Thiughts?

**Comment by stack72** [comment]
@lukehoban good points - I am more than happy to close this out - I am just trying to fix #478 

This functionality exists as part of the create in Eks already. I guess we can ask @metral if this is even needed any more :)

**Comment by lukehoban** [comment]
Yeah - not clear why that issue was in this repo - I would have assumed we would address it in the EKS repo. But not 100% sure I follow what the issue is asking for - so perhaps need to confirm with @metral before making any change here.

**Comment by stack72** [comment]
@lukehoban Azure, AWS and GCP all had the issue. Here's the same issue in GCP https://github.com/pulumi/pulumi-gcp/issues/97

**Comment by metral** [comment]
Thanks for taking the lead and working on this @stack72.

IIRC https://github.com/pulumi/pulumi-aws/issues/478, https://github.com/pulumi/pulumi-azure/issues/186, and https://github.com/pulumi/pulumi-gcp/issues/97 were concerned with addressing the generation of kubeconfig files for cluster's that were **not** created using Pulumi.

The use case specifically is if a user created a cluster by some other means that was not Pulumi, they could `.get()` the cluster using it's name, and this would return the cluster object, but it would be void of a kubeconfig prop as we create natively expose for EKS, AKS, and GKE via Pulumi.

> Yeah - not clear why that issue was in this repo - I would have assumed we would address it in the EKS repo

Correct, this is addressed in the `pulumi/eks` repo, but it was opened here as the `.get()` method for the `aws.eks.Cluster` object lives in this repo:

https://github.com/pulumi/pulumi-aws/blob/4747717488d91a764f03015aba5b3a6d84b6f01b/sdk/nodejs/eks/cluster.ts#L108-L119

IIUC this PR is replicating what we already handle for Pulumi created clusters, so it's not needed here.

We can certainly talk through if we still want to support the ability to import clusters created outside of Pulumi, and how we can create parity to Pulumi created clusters with props like the `kubeconfig`.

**Pull request closed without merging**
