### PR TITLE
Add hypothetical IAM helpers

### PR DESCRIPTION
**Pull request by joeduffy**
Per Slack conversation with @CyrusNajmabadi, this is one hypothetical approach to https://github.com/pulumi/pulumi-awsx/issues/242. This helps to reduce examples like

```typescript
const baseIamRole = new aws.iam.Role("baseIamRole", {
    path: "/",
    assumeRolePolicy: {
        "Version": "2012-10-17",
        "Statement": [{
            "Action": [
                "sts:AssumeRole",
            ],
            "Effect": "Allow",
            "Principal": {
                "Service": [
                    "ec2.amazonaws.com",
                ],
            },
        }],
    },
});
```

to the far simpler

```typescript
const baseIamRole = new aws.iam.Role("baseIamRole", {
    path: "/",
    assumeRolePolicy: aws.iam.createPolicy({
        action: "sts:AssumeRole",
        servicePrincipal: "ec2.amazonaws.com",
    }),
});
```

Of course, this is a vast subset of what we can do -- I think there are many interesting examples for things like `attachPolicy` on `User`, etc. But anyway, just an example approach for consideration.

### CODE REVIEW

**Comment by joeduffy** [comment]
@lukehoban What do you think about this approach? I've been using it on some projects recently and, though simple, it really does clean up some of the strange/hard-coded IAM policies. I can personally never remember things like the version number, etc. This could be a nice/minor add for the launch.

**Comment by CyrusNajmabadi** [comment]
I'd go even further.  i..e have `awsx.iam.assumeRolePolicy("ec2.amazonaws.com")`.  I think there are ample areas where we can drive simple entrypoints to create this stuff.  

However, i don't see a huge rush on this, and i'd really like a good 48-72 hours spent on collecting lots of the use cases and driving toward a nice API for all those cases.

**Comment by casey-robertson** [comment]
upvote - doing AWS policies in code is a dumpster fire.

**Comment by lukehoban** [comment]
@casey-robertson Anything in particular you'd like to see made simpler?

Note that we already have `aws.iam.assumeRolePolicyForPrincipal` - so the original code example above can be:

```
const baseIamRole = new aws.iam.Role("baseIamRole", {
    path: "/",
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({Service: "ec2.amazonaws.com" }),
});
```

The changes in this PR provide a bit of additional flexibility - and might be useful - but would love to hear your use cases (possibly in a new issue) to make sure we do work that addresses them.

**Comment by thomas11** [comment]
closed after confirming with lukehoban.

**Pull request closed without merging**
