### PR TITLE
Update pulumi-terraform version

### PR DESCRIPTION
**Pull request by swgillespie**
Also includes a change to `resources.go` to bump the version constraint on `pulumi` to be `>=0.16.0`.

### CODE REVIEW

**Comment by pgavlin** [comment]
Would you mind bringing in the Go changes as well (`pulumi-terraform` at commit c08676f1cfcf3bb871ef20e60ce7ba7c7570fffb)?

**Comment by swgillespie** [comment]
@pgavlin done, will push in a minute.

Oh goodness, looks like there's a Python example in this repo - I'm going to skip them and tag with https://github.com/pulumi/pulumi/issues/2138.

**Comment by swgillespie** [comment]
@pgavlin looks like the Go example might be busted.

**Comment by pgavlin** [comment]
Yeah, you’ll also need to bump the `pulumi/pulumi` version.

**Comment by swgillespie** [comment]
cool, will do.

**Comment by pgavlin** [comment]
The Go example is now fixed. The latest failure is kind of an odd one in the `topic` example: https://travis-ci.com/pulumi/pulumi-aws/builds/90306471#L2672-L2711

**Comment by pgavlin** [comment]
Logged a bug for follow-up: https://github.com/pulumi/pulumi-aws/issues/363

**Pull request merged**
