### PR TITLE
Update auto-generated AWS managed IAM policies

### PR DESCRIPTION
**Pull request by auvred**
It's been over a year since the last time IAM policies were synchronized - https://github.com/pulumi/pulumi-aws/pull/2393

[Deprecated policies list](https://github.com/zoph-io/MAMIP/blob/48e32c4b7f4d72e67fc5520a62ce11b63fb3bc5f/DEPRECATED.json)

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Hi @auvred, thanks for raising the PR! It looks sensible. I've started the acceptance tests and if that passes it should be good to go. I'll let @iwahbe have a look too as he is likely more familiar with this.

**Comment by auvred** [comment]
@VenelinMartinov looks like Python SDK build is failing: https://github.com/pulumi/pulumi-aws/actions/runs/8327415042/job/22786537436

The changes in the `sdk/python/pulumi_aws/iam/_enums.py` were made by running `make build_python` locally, so, as far as I understand it, it should be fine.

Is there anything I can do on my side to resolve this?

**Comment by iwahbe** [comment]
This PR builds cleanly for me, so I'm going to assume the diff is an artifact of the way we are running PRs tests for external contributors. I'm going to merge and then fix-up master if it becomes a problem, though I don't think it will.

**Comment by auvred** [comment]
> I'm going to try to merge as #3701.

Nice! Then I'm closing this pr.

**Pull request closed without merging**
