### PR TITLE
Add Support for Java17 Runtime

### PR DESCRIPTION
**Pull request by elrxii**
Add support for Java 17 runtime.

### CODE REVIEW

**Comment by a1flecke** [comment]
This is awesome.  We can use this

**Comment by a1flecke** [comment]
@lukehoban what is needed to get this over the line?  This will really help us.

**Comment by elrxii** [comment]
@a1flecke I messaged in their Slack and was told the Pulumi team is out this week but will be back next week.

**Review by lukehoban — APPROVED** [review]

**Pull request merged**
