### PR TITLE
Upstream v5.63.0

### PR DESCRIPTION
**Pull request by t0yv0**
Upgrade upstream to [5.63.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.63.0)

Fixes https://github.com/pulumi/pulumi-aws/issues/4373
Fixes https://github.com/pulumi/pulumi-aws/issues/4372
Fixes https://github.com/pulumi/pulumi-aws/issues/3713
Fixes https://github.com/pulumi/pulumi-aws/issues/4369

There are some changes to patches:

- https://github.com/pulumi/pulumi-aws/issues/4369 is removed as it is part of upstream now 

- https://github.com/pulumi/pulumi-aws/issues/3713 is removed as there was no clean conflict resolution; this patch is under test so if test suite passes the removal is safe

- https://github.com/pulumi/pulumi-aws/issues/2746 patch is edited to remove rds/security_group resource code that got removed upstream but was preserved in patches. This code appears to be dead / unused code but continues to generate conflicts

- added a patch for gamelift.Matchmaking* resources; these are [deprecated](https://github.com/pulumi/pulumi-aws/issues/4375) but remain supported until the next major release. Upstream moved gamelift to Go SDK v2 so the patch is needed to preserve the Go SDK v1 code for these resources without re-coding them.

- added a patch to fix tags for new PF-based resources; this can go away once we land https://github.com/pulumi/pulumi-aws/pull/4151

### CODE REVIEW

**Comment by t0yv0** [comment]
Regression detected by the tests:

```
 panic: no AWS SDK v1 API client factory: gamelift
```

This is not entirely surprising as the gamelift patch edits must not be complete. I'll tackle this.

**Comment by flostadler** [comment]
@t0yv0 I adapted the patch a bit, it was missing some of the code to setup the `conn` and resolve the endpoint. Worked locally for me after fixing that up 🤞

**Review by corymhall — APPROVED** [review]
I think the only upstream tests we need to run are related to the gamelift patch. The other patch updates look minor.

**Comment by t0yv0** [comment]
@corymhall these gamelift resources are not in upstream and are not under test. I think we don't have any more information here from running upstream tests.

**Comment by corymhall** [comment]
@t0yv0 
> these gamelift resources are not in upstream and are not under upstream test,

It looks like we added upstream tests as part of the patch

https://github.com/pulumi/pulumi-aws/blob/db316a3c9c6bea1a35263b0137976bef421d70dd/patches/0014-add-matchmaking-configuration-72.patch#L432

**Comment by AshTharappel** [comment]
Thanks for working on this. I am currently affected by the on JobQueue issue, so I appreciate y'all already being on top of it.

**Comment by flostadler** [comment]
Running the gamelift tests worked for our added resources:
```
~ TF_ACC=1 go test ./internal/service/gamelift/... -v -count 1 -parallel 20 -run=TestAccMatchmakingConfiguration -timeout 180m

=== RUN   TestAccMatchmakingConfiguration_basic
=== PAUSE TestAccMatchmakingConfiguration_basic
=== RUN   TestAccMatchmakingConfiguration_tags
=== PAUSE TestAccMatchmakingConfiguration_tags
=== RUN   TestAccMatchmakingConfiguration_disappears
=== PAUSE TestAccMatchmakingConfiguration_disappears
=== CONT  TestAccMatchmakingConfiguration_basic
=== CONT  TestAccMatchmakingConfiguration_disappears
=== CONT  TestAccMatchmakingConfiguration_tags
--- PASS: TestAccMatchmakingConfiguration_disappears (28.34s)
--- PASS: TestAccMatchmakingConfiguration_tags (32.40s)
--- PASS: TestAccMatchmakingConfiguration_basic (34.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/gamelift	38.718s

~ TF_ACC=1 go test ./internal/service/gamelift/... -v -count 1 -parallel 20 -run=TestAccMatchmakingRuleSet -timeout 180m

=== RUN   TestAccMatchmakingRuleSet_basic
--- PASS: TestAccMatchmakingRuleSet_basic (27.96s)
=== RUN   TestAccMatchmakingRuleSet_disappears
=== PAUSE TestAccMatchmakingRuleSet_disappears
=== CONT  TestAccMatchmakingRuleSet_disappears
--- PASS: TestAccMatchmakingRuleSet_disappears (21.12s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/gamelift	53.225s
```

**Pull request merged**
