### PR TITLE
Spelling correction of fdqn to fqdn

### PR DESCRIPTION
**Pull request by nille**
Correcting minor spelling error: ~fdqn~ fqdn

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
@nille I'm sorry for such a long delay. It looks the PR needs a rebase to satisfy our CI, could you please do that?

**Comment by nille** [comment]
@mikhailshilkov Done ✅

**Review by mikhailshilkov — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
Thank you!

**Pull request merged**
