### PR TITLE
Upgrade to v4.36.1

### LINKED ISSUE #2186: Upgrade terraform-provider-aws to v4.36.0
Release details: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.36.0

### LINKED ISSUE #2189: Upgrade terraform-provider-aws to v4.36.1
Release details: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.36.1

### PR DESCRIPTION
**Pull request by danielrbradley**
Fixes #2189 
Fixes #2186 

Upstream diff: https://github.com/pulumi/terraform-provider-aws/compare/upstream-v4.35.0...upstream-v4.36.1

### CODE REVIEW

**Comment by thomas11** [comment]
> Resource "aws:simpledb/domain:Domain" missing
> Function "aws:index/getCallerIdentity:getCallerIdentity" missing
> Function "aws:globalaccelerator/getAccelerator:getAccelerator" missing
> Type "aws:globalaccelerator/getAcceleratorIpSet:getAcceleratorIpSet" missing
> Type "aws:globalaccelerator/getAcceleratorAttribute:getAcceleratorAttribute" missing

@danielrbradley , did you look into these missing entities, particularly the resource? Seems like they're still present in your PR?

**Comment by viveklak** [comment]
Is this expected? I would have expected a much smaller footprint of commits in the diff link you mentioned?
Screen Shot 2022-10-26 at 8 55 06 AM

**Comment by danielrbradley** [comment]
@viveklak the nubmer of commits is fine - it's just a side-effect of how long ago we did the fork

@thomas11 I think the removals need investigating for sure. Wouldn't be too worried about the examples, but worth sanity checking if that was from a source change

**Comment by danielrbradley** [comment]
> Resource "aws:simpledb/domain:Domain"

Appears to have been moved to the new framework - we'll need to revert. This has been removed on line 2080 of `internal/provider/provider.go`

>Function "aws:index/getCallerIdentity:getCallerIdentity" 

This has been removed on line 914 of `internal/provider/provider.go`

> Function "aws:globalaccelerator/getAccelerator:getAccelerator"

I had to revert changes here - it's possible that there was also a reference to it that was removed - `aws_globalaccelerator_accelerator` on line 668 of `internal/provider/provider.go`

>Type "aws:globalaccelerator/getAcceleratorIpSet:getAcceleratorIpSet" missing
>Type "aws:globalaccelerator/getAcceleratorAttribute:getAcceleratorAttribute" missing

These are most likely just knock-on changes from the resources/data sources which I'd hope get resolved when the above get fixed.

**Comment by danielrbradley** [comment]
@thomas11 I'm hopeful this will sort us out. It looks like the docs are back - probably were removed because they used `aws.getCallerIdentity` which was missing, so it skipped the docs generation.

**Pull request merged**
